### ISSUE TITLE
Dev registration does not result in agent

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#90]
When I sign up when starting at http://devstore.rerum.io, the resulting user in Auth0 does not have an agent.  This is a blocking issue and needs attention ASAP.

**Comment by thehabes** [comment]
our server is so smart

create object
verify a JWT access token
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vZGV2c3RvcmUucmVydW0uaW8vdjEvYWdlbnQiOiJodHRwOi8vZGV2c3RvcmUucmVydW0uaW8vdjEvaWQvNWIyYzBkNWRlNGIwZmM1ZDRhZWI3MDlmIiwiaXNzIjoiaHR0cHM6Ly9jdWJhcC5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWIyYzBkNWIxNDc0MWYyYTYyZjIxYWNmIiwiYXVkIjpbImh0dHA6Ly9yZXJ1bS5pby9hcGkiLCJodHRwczovL2N1YmFwLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE1MzE0MjMyNDMsImV4cCI6MTU2Mjk4MDg0MywiYXpwIjoiNjJKc2E5TXhIdXFoUmJPMjBnVEhzOUtwS3I3VWU3c2wiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBvZmZsaW5lX2FjY2VzcyJ9.p0Lth51-bcTwpCyFBKnm8lzpA13OGpGuOHw-4qpzKwKtgg-u7FIXaVmIcPK3umbcU--sRxOFbv9ts3CVIT5N9LsozorPK6OORW8CgOI-ycnGcLUxqKmIWkOMzZqJM_-9kF7VBql0bXVp6rKGK8ow0-ChLq-AK1JouoJ22WcgZiP_I07VM3t3mmzzgeLiN8pd9QzO-Gr8FtnIkYs5l1btUIafpJrFEDJiRUURnuBoQZ88rQ1zi3K6XAmgZDTWsbec2EkGQRkekaTuL29PJlFJIyNQyqb9OHDhGCqsYlshTeTOhEYkCD6jsiAvUbQEp-w2D_u2eHDPgS8JLKKzsaPY6w
initialize cache...
check cache for key...
Verification failed.  We were given a bad token.  IP fallback.  Exception below, but caught.
17-Oct-2019 10:21:37.230 SEVERE [ajp-nio-8109-exec-1371] edu.slu.action.ObjectAction.verifyAccess null
 com.auth0.jwt.exceptions.TokenExpiredException: The Token has expired on Fri Jul 12 20:20:43 CDT 2019.
        at com.auth0.jwt.JWTVerifier.assertDateIsFuture(JWTVerifier.java:441)
        at com.auth0.jwt.JWTVerifier.assertValidDateClaim(JWTVerifier.java:432)
        at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:373)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:355)
        at edu.slu.action.ObjectAction.verifyAccess(ObjectAction.java:2610)
        at edu.slu.action.ObjectAction.methodApproval(ObjectAction.java:688)
        at edu.slu.action.ObjectAction.saveNewObject(ObjectAction.java:1350)
        at sun.reflect.GeneratedMethodAccessor463.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:450)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:289)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252)
        at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:256)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:176)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265)
        at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:68)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:249)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:249)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:191)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:252)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:100)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:141)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:145)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
        at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:176)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:187)
        at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
        at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
        at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:546)
        at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:77)
        at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:91)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)

[Modifying Data Request]: ip ========== 35.167.74.121@2019-10-17 10:21:37 +++++ The app needs to register with RERUM
I need a generator out of all this.  Did I get it: http://devstore.rerum.io/v1/id/5b2c0d5de4b0fc5d4aeb709f
Here is the error response json object to return with status 401
{"code":401,"message":"Could not authorize you to perform this action.  Have you registered at http://devstore.rerum.io/v1/"}
Write errore response completed
create approved? false

**Comment by thehabes** [comment]
The token expiration should be caught and RERUM should be using the TinyTokenManager to use the refresh token to get a new access token.  Maybe this specific exception is not caught or something.  If this means the refresh token expired, we have a different problem because they should never expire.

**Comment by thehabes** [comment]
@cuabp I am unassigning you.  I set this up so theoretically I will be most efficient at finding a solution.

**Comment by thehabes** [comment]
FML, rerum_server does not have a TokenManager class for its bots, I did not think about that.  As the application owners that registered rerum_server with the RERUM API, we are responsible for ensuring our access token is not expired.  TinyThings suggests doing this with something like its example TinyTokenManager.java.  

The only thing this affects about rerum_server is it's ability to use the bots to create things, which is only our internal code.  In particular, we use the bots to make new sign up agents via an Auth0 rule.  This, of course, requires a valid access_token for create.action.  The bots have one, but they expire like everyone else and need to be refreshed, which rerum_server does not do.

This means all new user sign ups since the expiration date are useless.  Prod will soon suffer the same fate without a fix.

**Many, many NSFW expletives

**Comment by cubap** [comment]
I'm glad we are finding this instead of diagnosing it after the fact. I understand what you are doing, so let me know if you need me to get into it, but I understand that you are completely diverted right now.

**Comment by thehabes** [comment]
OOooof...the Auth0 Client holds the dev and prd bot access_token.  This means we would need to write a TokenManager rule that we can use in other rules when those rules detect an expired token...I am not sure we can make rerum_server do this, since it does not keep track of the bot tokens, since it does not discern what user is doing what .action, just whether or not that access_token provided with that action is valid.  It is not up to rerum_server to refresh your token for you (which we retroactively applied to our own tokens).  

A bit goofy here, this needs a conversation.

**Comment by thehabes** [comment]
Here was the decision:
This is not a rerum_server issue.  It is a token management issue.  Yes, rerum_server has bots, but as an API it is not responsible for keeping any registered application's tokens up to date.

The Token Managers (OngCDH @ SLU) were contacted and warned that their token had expired.  In response, the developers use http://devstore.rerum.io/v1/ to get a new refresh token and a new access token.  They put their new access token into their software and the problem was solved.
